# Generated by Django 3.2 on 2022-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='asset',
            name='print_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
