# Generated by Django 3.2 on 2022-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20220421_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
